### ISSUE TITLE
collecties - alfabetisch sorteren op naam

### ISSUE THREAD

**Issue by roxannewyns** [libis/CAG#184]
assigned @JorisLambrechts 

Kunnen de zoekresultaten van collecties alfabetisch gesorteerd worden op "Naam Instelling"?

**Comment by JorisLambrechts** [comment]
Enkel degenen die op die pagina verschijnen, maar die zijn al gesorteerd op id, dus eigenlijk niet.

Ik kan er een issue van maken bij de solrsearch plugin?

**Comment by roxannewyns** [comment]
Ok ik zal het zo doorgeven. Maar maak maar een issue aan bij de solrplugin want we gaan dit ook nodig hebben voor nabucco.

**Comment by JorisLambrechts** [comment]
Er was eerder al een issue blijkbaar https://github.com/scholarslab/SolrSearch/issues/25
 "We're stuck between two systems, here. Because we want to define fields dynamically and because all fields in Omeka can take multiple values, they all have to be marked multiValue for Solr. But Solr cannot sort multivalue fields."
